/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bai77;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author Louis
 */
public class frmTinhNgaySinh extends javax.swing.JFrame {

    /**
     * Creates new form frmTinhNgaySinh
     */
    public frmTinhNgaySinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblKetQua = new javax.swing.JLabel();
        txtNgay = new javax.swing.JTextField();
        txtThang = new javax.swing.JTextField();
        txtNam = new javax.swing.JTextField();
        btnTinh = new javax.swing.JButton();
        lblThongBaoNgay = new javax.swing.JLabel();
        lblThongBaoThang = new javax.swing.JLabel();
        lblThongBaoNam = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("                       Tính ngày sinh");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Tính ngày sinh");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Nhập ngày:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Nhập tháng:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Nhập năm:");

        lblKetQua.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        txtNgay.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        txtThang.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        txtNam.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        btnTinh.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnTinh.setText("Tính");
        btnTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhActionPerformed(evt);
            }
        });

        lblThongBaoNgay.setForeground(new java.awt.Color(255, 0, 0));

        lblThongBaoThang.setForeground(new java.awt.Color(255, 0, 0));

        lblThongBaoNam.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(22, 22, 22)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNgay)
                            .addComponent(txtThang)
                            .addComponent(txtNam, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblThongBaoNgay)
                            .addComponent(lblThongBaoThang)
                            .addComponent(lblThongBaoNam)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblKetQua))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btnTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThongBaoNgay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThongBaoThang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThongBaoNam))
                .addGap(18, 18, 18)
                .addComponent(lblKetQua)
                .addGap(37, 37, 37)
                .addComponent(btnTinh)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhActionPerformed
        // TODO add your handling code here:
        if (txtNgay.getText().equals("") || txtThang.getText().equals("") || txtNam.getText().equals("")){
            lblKetQua.setText("Bạn nhập dữ liệu không đầy đủ");
        }
        else
        {
            int day = Integer.parseInt(txtNgay.getText());
            int month = Integer.parseInt(txtThang.getText());
            int year = Integer.parseInt(txtNam.getText());
            if (day <= 0 || day > 31)
                lblThongBaoNgay.setText("Ngày nhập không hợp lệ");
            else if (month <= 0 || month > 12)
                    lblThongBaoThang.setText("Tháng nhập không hợp lệ");
            else if (txtNam.getText().length() != 4 || year <= 0)
                    lblThongBaoNam.setText("Năm nhập vào không hợp lệ");
            else{
                // Lấy thời gian hiện tại
                Calendar now = Calendar.getInstance();

                // Lấy ngày tháng năm hiện tại
                int currentDay = now.get(Calendar.DAY_OF_MONTH);
                int currentMonth = now.get(Calendar.MONTH)+1;
                int currentYear = now.get(Calendar.YEAR);

                // Tính số ngày
                SimpleDateFormat myFormat = new SimpleDateFormat("dd MM yyyy");
                String inputDate = String.valueOf(day) + " " + String.valueOf(month) + " " + String.valueOf(currentYear);
                String nowDate = String.valueOf(currentDay) + " " + String.valueOf(currentMonth) + " " + String.valueOf(currentYear);
                try{
                    Date date1 = myFormat.parse(inputDate);
                    Date date2 = myFormat.parse(nowDate);
                    long diff = date2.getTime() - date1.getTime();
                    float days = (diff / (1000*60*60*24));
                    if (days > 0)
                        lblKetQua.setText("Ngày sinh nhật của bạn đã qua " + (int)days + " ngày");
                    else if (days == 0)
                        lblKetQua.setText("Hôm nay là ngày sinh nhật của bạn. Chúc mừng sinh nhật");
                    else
                        lblKetQua.setText("Còn " + (int)Math.abs(days) + " ngày nữa là đến sinh nhật của bạn");
                }
                catch(ParseException e){
                }
            }
        }
    }//GEN-LAST:event_btnTinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTinhNgaySinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTinhNgaySinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTinhNgaySinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTinhNgaySinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTinhNgaySinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblKetQua;
    private javax.swing.JLabel lblThongBaoNam;
    private javax.swing.JLabel lblThongBaoNgay;
    private javax.swing.JLabel lblThongBaoThang;
    private javax.swing.JTextField txtNam;
    private javax.swing.JTextField txtNgay;
    private javax.swing.JTextField txtThang;
    // End of variables declaration//GEN-END:variables
}
